--- # This is for making handlers

- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
    - name: Install apache server on centos
      apt:
        name: apache2
        state: present
      notify: restart apache server # Notify attribute will tell which handler is going to run after execution of current task

  # in handler section we will provide all the handlers
  handlers: 
    - name: restart apache server
      # Everyting is same as task
      service:
        name: apache2
        state: restarted
